context.modules = [
  {
    name = libpipewire-module-parametric-equalizer
    args = {
      equalizer.filepath = "$HOME/.config/meloid/eq/%eqId%.txt"
      equalizer.description = "Meloid EQ"
      
      audio.channels = 2
      audio.position = [ FL FR ]

      capture.props = {
        media.class = "Audio/Sink"
        node.name = "meloid_eq"
        node.description = "Meloid EQ"
        media.name = "Meloid EQ"
      }

      playback.props = {
        node.passive = true
        node.name = "meloid_eq_output"
      }
    }
  }
]