# yaml-language-server: $schema=https://github.com/DexerMatters/meloid/raw/master/assets/config.schema.yaml
$schema: https://github.com/DexerMatters/meloid/raw/master/assets/config.schema.yaml
showWelcome: true
colorMode: auto
eq: default
